version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    hostname: mongodb
    env_file:
      - .env
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./database/db/:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.41.0
    hostname: prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./database/prom/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=1y'
      - '--storage.tsdb.retention.size=100GB'
      - '--web.enable-lifecycle'
    user: "0"