version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    hostname: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./database/db/:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5