---
  - hosts: c_clients
    gather_facts: false
    tasks:

    - name: Check for limit argument
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'c_clients' or -l 'c2,d2'"
      when: ansible_limit is not defined
      run_once: true

    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps

    - debug: var=ps.stdout_lines