---
  - hosts: c_clients

    gather_facts: false
    
    tasks:


    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'c_clients'"
      when: ansible_limit is not defined
      run_once: true

    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps
      
    #- name: sad
    #  ansible.builtin.command: 
    #    cmd: 'ps -eo pcpu,user,args | sort -r -k1 | head -n5
    #  register: myoutput

    - debug: var=ps.stdout_lines