---

  - hosts: c1
    gather_facts: false
    tasks:
      
    - name: Update the /etc/hostname file
      become: true
      ansible.builtin.template:
        src: hostname.j2
        dest: /etc/hostname

    - name: Update the /etc/hosts file
      become: true
      lineinfile: 
        dest: /etc/hosts
        regexp: ^127.0.1.1*
        line: 127.0.1.1 {{hostname}}

    - name: Reboot
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600