---
# Copy the ssh key to the remote server

- hosts: clients
  gather_facts: false
  tasks:
  
  - name: Copy the private key
    ansible.builtin.copy:
      src: ./.ssh/id_ecdsa
      dest: ~/.ssh/id_ecdsa
      mode: '0600'

  - name: Copy the public key
    ansible.builtin.copy:
      src: ./.ssh/id_ecdsa.pub
      dest: ~/.ssh/id_ecdsa.pub
      mode: '0644'

- hosts: server-a
  tasks:

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: agpbruger
      state: present
      key: "{{ lookup('file', '.ssh/id_ecdsa.pub') }}"
