---

  - hosts: clients, server-a
    gather_facts: false
    tasks:
      
    - name: Pull the latest code
      ansible.builtin.git:
        repo: 'git@github.com:Master2022E/OnionRTC-experiment.git'
        dest: ./OnionRTC-experiment
        version: main
        clone: yes
        update: yes
        accept_hostkey: true

  - hosts: clients
    gather_facts: false
    tasks:

    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: ~/OnionRTC-experiment/requirements.txt



  - hosts: server-a
    gather_facts: false
    tasks:

    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: ~/OnionRTC-experiment/CommandAndControl/requirements.txt
