version: '3.3'
services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: always
    ports:
      - "7080:7080"
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data # Optional
      - ./caddy/config:/config # Optional

  webrtc:
    container_name: webrtc
    image: thomsen96/webrtc-server:latest
    restart: always
    env_file:
      - ./webrtc/.env

  signal:
    container_name: signal
    image: thomsen96/signal-server:latest
    restart: always

  observer:
    container_name: observer
    restart: always
    image: observertc/observer:1.0.0-beta
    env_file:
      - ./observer/.env
    volumes:
      - ./observer/config_observer.yaml:/config_observer.yaml
      - ./observer/config_micronaut.yaml:/config_micronaut.yaml

  mongodb:
    container_name: mongodb
    image: mongo:4.2
    hostname: mongodb
    restart: always
    env_file:
      - ./mongo/.env
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /media/storage/db:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
